name: WebAPI Docker Publish

on:
  push:
    branches:
      - "main"
    paths:
      - Org.WebAPI/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./Org.WebAPI
          push: true
          tags: dchennaraidu/otel-webapi:latest
